<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hamle</string>
		<string>hamle-snip</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^( *?)[^\s].*$</string>
	<key>foldingStopMarker</key>
	<string>^\1\s</string>
	<key>name</key>
	<string>HAMLE</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^( *?)/</string>
			<key>end</key>
			<string>^(?!(?:\s*$|\1\s))</string>
			<key>name</key>
			<string>comment.block.hamle</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^( *?):css</string>
			<key>end</key>
			<string>^(?!(?:\s*$|\1\s))</string>
			<key>name</key>
			<string>source.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bardollarvar</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^( *?):javascript</string>
			<key>end</key>
			<string>^(?!(?:\s*$|\1\s))</string>
			<key>name</key>
			<string>source.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^( *?):html</string>
			<key>end</key>
			<string>^(?!(?:\s*$|\1\s))</string>
			<key>name</key>
			<string>source.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.html</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^ *(?:(?:([a-zA-Z0-9][a-zA-Z0-9_]*)(#[a-zA-Z0-9\_]+)?(\.[a-zA-Z0-9\_]+)?)|(?:(#[a-zA-Z0-9\_]+)(\.[a-zA-Z0-9\_]+)?)|(\.[a-zA-Z0-9\_]+))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.hamle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.id.hamle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.class.hamle</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.id.hamle</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.quoted.class.hamle</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.quoted.class.hamle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#paramlist</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bardollarvar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dollarvar</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^ *\|[a-zA-Z]+</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>keyword.control.hamle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dollarvar</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^ *(_) </string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hamle</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>plain.text.hamle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bardollarvar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dollarvar</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bardollarvar</key>
		<dict>
			<key>match</key>
			<string>{\$[^}]+}</string>
			<key>name</key>
			<string>variable.parameter.bardollar.hamle</string>
		</dict>
		<key>dollarvar</key>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z][a-zA-Z0-9_]+</string>
			<key>name</key>
			<string>variable.parameter.bardollar.hamle</string>
		</dict>
		<key>paramlist</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>contentName</key>
			<string>string.other.hamle</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>plain.text.hamle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dollarvar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bardollarvar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#paramlistvars</string>
				</dict>
			</array>
		</dict>
		<key>paramlistvars</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.hamle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.function.hamle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z0-9]+)(=)|[^\&amp;](\&amp;)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.hamle</string>
	<key>uuid</key>
	<string>b966e1a6-c12d-4281-b791-1850dba2291c</string>
</dict>
</plist>
